language: c
sudo: false

addons:
  apt:
    packages:
      - pandoc

branches:
  only:
    - master

install:
    - source devtools/travis-ci/install_miniconda.sh
    - conda config --add channels omnia

script:
  # Build docs only on 3.5, but return success even if that check fails
  conda build --quiet devtools/conda-recipe
  && { [[ $CONDA_PY = 3.5 ]] && devtools/travis-ci/build_docs.sh } || true; }

env:
  matrix:
    - CONDA_PY=2.7 CONDA_NPY=1.11
    - CONDA_PY=3.4 CONDA_NPY=1.10
    - CONDA_PY=3.5 CONDA_NPY=1.11

deploy:
  - provider: s3
    access_key_id:
      secure: "C0rtKtVHzdmaofuGDFkZljzvnZCRB0irXIHsFcQ6Cocf8V7rmYvuIpKxzlfQkI6RMBQ4bmzUe2z2XsvKwweUJFHur9Wc9mI+b4dBPcTR+ewwVzYs0nML6vSU7SYseMhJndnlD6J/WpP6vyrJ4YQIcYvRvqN1Qn6Mn2Kk8EagySM="
    secret_access_key:
      secure: "V9R4Nid8E19iymAPqpc5RIPB9Nkvx5N2iB66lQrHGyn2nZjoo6Cp+mbon/Ow/Ot9BWWa7NA1ihJUvs+in3WKIDPfiPiN6qgCE6j35VZJaDqeU5SW/6mbd6CqZEEFy3mA0EDeIIFFvWLnuLyStOJPFKPI/vkrkLxzNhcENSDIc4Q="
    bucket: "msmbuilder.org"
    skip_cleanup: true
    local_dir: docs/_deploy/
    on:
      branch: master
      condition: "$CONDA_PY = 3.5"
