language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  - python setup.py -q install
  - nosetests Mixtape/tests -v

env:
  matrix:
    - python=2.7
    - python=3.3
    - python=3.4
  global:
    # For pushing docs to S3:
    # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - secure: "U2tY/Y6BBgpDR6FQP/bX7Hm89MadrlIeyuviAwbejJ7REb+ppWWY4pfvmVKhGFoPjOgLdvTdioarJUZHtbujTNkEsI9d6JW99YYdHuMruj9Y/1mwbDJdric1jBg29sqc6NSycaTNa/uiL8EDJBJI/JLN9GcCModbO7QbqlbhNns="
    - secure: "K36Ags61kE9/+iSvN6N3Pzi6QIB6z4g25wdNlK4HBjxW90MFMDhvR3OMw6yJgNgFu5A95lTlIsUnqqx3tbQdqX/+XY4aMPIGzVIRKWpYS6d9+HoNO1d85sGy78dpGsybDR7AdsKi2SkoxYVmwD1CSUoA/S8pE3fIb5Ou28DKKyQ="

after_success:
  - source devtools/ci/after_sucess.sh
