language: c
sudo: false

addons:
  apt:
    packages:
      - pandoc

branches:
  only:
    - master

install:
    - source devtools/travis-ci/install_miniconda.sh
    - conda config --add channels omnia

script:
  # Run tests. If they succeed, build docs only on 3.6
  conda build --quiet devtools/conda-recipe
  && if [[ $CONDA_PY = 3.6 ]]; then devtools/travis-ci/build_docs.sh; fi

env:
  matrix:
    - CONDA_PY=2.7 CONDA_NPY=1.12
    - CONDA_PY=3.5 CONDA_NPY=1.11
    - CONDA_PY=3.6 CONDA_NPY=1.12

deploy:
  - provider: s3
    access_key_id:
      secure: "av04wLV7wRmFjPRkDPE0FXNtvL51F597+DzUmrycLnI+Ltg5rxrxEUv2JMr7K1WrTTR1STFNhJBp6aQUwD3zzaA7N/1c0zY9ri35ML75LC/10IDb6UNbY6uPNqbP1co451OSz7tpGbu3JBL/TRL7MkReFbZxPLHPPP1ad/4O6nA="
    secret_access_key:
      secure: "c4b2fliqot9ZnI5cyTqEXSHQnCao+GoxmR+SJAcSURv381O/z3frlJX7pKf0qai2OrZSSdqX/wa2KdcWNeoDTKrTiCeKgFikc6x839tmjeQYVV0Y3hmSvZCzCFOAXyMf9GfJJ7gLBOBHSzTTJWeZDLZB6nuoi4Xw9Blgid6QxIs="
    bucket: "msmbuilder.org"
    skip_cleanup: true
    local_dir: docs/_deploy/
    on:
      branch: master
      condition: "$CONDA_PY = 3.6"
