language: c
sudo: false

addons:
  apt:
    packages:
      - pandoc

branches:
  only:
    - master

install:
  - source devtools/ci/install_miniconda.sh
  - export PYTHONUNBUFFERED=true
  # start Virtual X, so default matplotlib backend works
  # TOOD: fix tests so we don't need this.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  conda build devtools/conda-recipe
  && devtools/ci/build_docs.sh

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.4
    - CONDA_PY=3.5
  global:
    - CONDA_NPY=1.10
    # $BINSTAR_TOKEN (for user mpharrigan, with access to omnia)
    - secure: "DqDvfYriL3wYdQCp8pQM9huPQQ6U9dKWK02o0BhlAZque8mxU6MvZkp0GtajSqEPuVBjFeGOmFqzE5XgkLIs+vmniRyJ46hTDlOYIxgf2NA6AY6+xqVbqCIrq/xtIXPDPC0mXzASOdybAzdwv3VB/yq9G820o7qIWTg5yEg6qc0="

deploy:
  - provider: s3
    access_key_id:
      secure: "C0rtKtVHzdmaofuGDFkZljzvnZCRB0irXIHsFcQ6Cocf8V7rmYvuIpKxzlfQkI6RMBQ4bmzUe2z2XsvKwweUJFHur9Wc9mI+b4dBPcTR+ewwVzYs0nML6vSU7SYseMhJndnlD6J/WpP6vyrJ4YQIcYvRvqN1Qn6Mn2Kk8EagySM="
    secret_access_key:
      secure: "V9R4Nid8E19iymAPqpc5RIPB9Nkvx5N2iB66lQrHGyn2nZjoo6Cp+mbon/Ow/Ot9BWWa7NA1ihJUvs+in3WKIDPfiPiN6qgCE6j35VZJaDqeU5SW/6mbd6CqZEEFy3mA0EDeIIFFvWLnuLyStOJPFKPI/vkrkLxzNhcENSDIc4Q="
    bucket: "msmbuilder.org"
    skip_cleanup: true
    local_dir: doc/_deploy/
    on:
      branch: master
      condition: "$CONDA_PY = 3.4"
