language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7
    - python=3.3
    - python=3.4
  global:
    # For pushing docs to S3:
    # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - secure: "U2tY/Y6BBgpDR6FQP/bX7Hm89MadrlIeyuviAwbejJ7REb+ppWWY4pfvmVKhGFoPjOgLdvTdioarJUZHtbujTNkEsI9d6JW99YYdHuMruj9Y/1mwbDJdric1jBg29sqc6NSycaTNa/uiL8EDJBJI/JLN9GcCModbO7QbqlbhNns="
    - secure: "K36Ags61kE9/+iSvN6N3Pzi6QIB6z4g25wdNlK4HBjxW90MFMDhvR3OMw6yJgNgFu5A95lTlIsUnqqx3tbQdqX/+XY4aMPIGzVIRKWpYS6d9+HoNO1d85sGy78dpGsybDR7AdsKi2SkoxYVmwD1CSUoA/S8pE3fIb5Ou28DKKyQ="
    # BINSTAR_TOKEN
    - secure: "DISF0Evu4jZm/E3N+7At6nvsy+2yUScrEdOUc5nrX+f1nvtHfMo9L7Q/5LodF4/iD0zo046+xL/kLqlXbneMIgNyUrruGCliki1kefwEfzAPaYndC/ZIZQ3RcQ29rvu1ALv/x8KMiyC2N9h90P6RNi8YJ63Rjl8KRGa6N2cFlVM="

after_success:
  - source devtools/ci/after_sucess.sh
